-- Create messages table for Contact Form
create table messages (
  id bigint generated by default as identity primary key,
  first_name text not null,
  last_name text not null,
  email text not null,
  subject text not null,
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table messages enable row level security;

-- Allow anyone to insert (public contact form)
create policy "Allow public insert to messages" on messages for insert with check (true);

-- Allow only authenticated users (admins) to view messages
-- Note: You might need to adjust this if you don't have auth setup yet, 
-- but for now we'll allow public read for simplicity or strict admin read if you have auth.
-- For this demo/dev phase, we'll allow public read so you can verify it easily, 
-- but in production you should restrict this.
create policy "Allow public read to messages" on messages for select using (true);
