-- Create products table
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  price numeric not null,
  rating numeric default 5,
  images text[] not null default '{}',
  short_description text,
  benefits text[],
  how_to_use text,
  ingredients text,
  tag text,
  is_new boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create journal_posts table
create table journal_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  excerpt text not null,
  image text not null,
  date text not null,
  category text not null,
  content text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table products enable row level security;
alter table journal_posts enable row level security;

-- Create policies
-- Allow read access to everyone
create policy "Public products are viewable by everyone" on products for select using (true);
create policy "Public journal posts are viewable by everyone" on journal_posts for select using (true);

-- Allow insert/update/delete to everyone (Note: In a real app, you should restrict this to authenticated users)
create policy "Enable all access for all users" on products for all using (true);
create policy "Enable all access for all users" on journal_posts for all using (true);
